version: '3'
services:
  rabbit:
    restart: always
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest1"
      RABBITMQ_DEFAULT_PASS: "guest1"
    ports:
      - "15672:15672"
      - "5672:5672"
  discovery:
    restart: always
    image: xdevices/discovery:latest
    ports:
      - "8761:8761"
  proxy:
    restart: always
    image: xdevices/proxy:latest
    ports:
      - "8000:8000"
    environment:
      - EUREKA_SERVICE=http://discovery:8761/eureka
  dispatcher:
    restart: always
    image: dispatcher:latest
    environment:
      - HTTP_PORT=8100
      - SERVICE_NAME=dispatcher
      - EUREKA_SERVICE=http://discovery:8761
      - RABBIT_HOST=rabbit
      - PROXY_SERVICE=http://proxy:8000
    expose:
      - "8100"
  sensortypes:
    restart: always
    image: sensortypes:latest
    volumes:
      - /var/lib/jenkins/.databases/xdevices:/xdevices
    environment:
      - HTTP_PORT=8101
      - SERVICE_NAME=sensortypes
      - EUREKA_SERVICE=http://discovery:8761
      - DB_PATH=/xdevices/sensortypes.db
      - RABBIT_HOST=rabbit
    expose:
      - "8101"
  ui:
    restart: always
    image: ui:latest
    ports:
      - "80:80"
    expose:
      - "8105"
  register:
    restart: always
    image: register:latest
    volumes:
      - /var/lib/jenkins/.databases/xdevices:/xdevices
    environment:
      - HTTP_PORT=8102
      - EUREKA_SERVICE=http://discovery:8761
      - SERVICE_NAME=register
      - DB_PATH=/xdevices/register.db
      - RABBIT_HOST=rabbit
    expose:
      - "8102"
  eventslogger:
    restart: always
    image: eventslogger:latest
    volumes:
      - /var/lib/jenkins/.databases/xdevices:/xdevices
    environment:
      - HTTP_PORT=8103
      - EUREKA_SERVICE=http://discovery:8761
      - SERVICE_NAME=eventslogger
      - DB_PATH=/xdevices/eventslogger.db
      - RABBIT_HOST=rabbit
    expose:
      - "8103"
  servicesresolver:
    restart: always
    image: servicesresolver:latest
    environment:
      - HTTP_PORT=8104
      - EUREKA_SERVICE=http://discovery:8761
      - SERVICE_NAME=servicesresolver
      - RABBIT_HOST=rabbit
    expose:
      - "8104"
  temperaturearchive:
    restart: always
    image: temperaturearchive:latest
    volumes:
      - /var/lib/jenkins/.databases/xdevices:/xdevices
    environment:
      - HTTP_PORT=8105
      - EUREKA_SERVICE=http://discovery:8761
      - SERVICE_NAME=temperaturearchive
      - DB_PATH=/xdevices/temperaturearchive.db
      - RABBIT_HOST=rabbit
      - PROXY_SERVICE=http://proxy:8000
    ports:
      - "8105:8105"
