version: '3'
services:
  discovery:
    restart: always
    image: xdevices/discovery:latest
    ports:
      - "8761:8761"
  proxy:
    restart: always
    image: xdevices/proxy:latest
    ports:
      - "8000:8000"
    environment:
      - EUREKA_SERVICE=http://discovery:8761/eureka
  dispatcher:
    restart: always
    image: dispatcher:latest
    environment:
      - HTTP_PORT=8100
      - SERVICE_NAME=dispatcher
      - EUREKA_SERVICE=http://discovery:8761
    expose:
      - "8100"
  sensortypes:
    restart: always
    image: sensortypes:latest
    volumes:
      - /var/lib/jenkins/.databases/xdevices:/xdevices
    environment:
      - HTTP_PORT=8101
      - SERVICE_NAME=sensortypes
      - EUREKA_SERVICE=http://discovery:8761
      - DB_PATH=/xdevices/sensortypes.db
    expose:
      - "8101"
  ui:
    restart: always
    image: ui:latest
    ports:
      - "80:80"
